language: node_js
node_js:
  - "stable"
  - "4.0"
service_name: travis-pro
repo_token: wb3le6LKpBGGsWGDqKHWZ5TSxzjfLQGYi
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
